-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#0f1417',
  base01 = '#0a0f12',
  base02 = '#181c1f',
  base03 = '#41484d',
  base04 = '#c1c7ce',
  base05 = '#dfe3e7',
  base06 = '#2c3134',
  base07 = '#353a3d',

  base08 = '#ffb4ab',
  base09 = '#cbc1e9',
  base0A = '#b6c9d8',
  base0B = '#91cef5',
  base0C = '#494263',
  base0D = '#004c6a',
  base0E = '#374955',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#004c6a',
  fg = '#0f1417',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#e7deff',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#cbc1e9',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b6c9d8',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#1f6587',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0a0f12',
  fg = '#91cef5',
})
